// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AgentCommand.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CUSTOM_MSGS_MSG_AGENTCOMMAND_H_
#define _FAST_DDS_GENERATED_CUSTOM_MSGS_MSG_AGENTCOMMAND_H_

#include "geometry_msgs/msg/Point.h"
#include "std_msgs/msg/Int8.h"
#include "std_msgs/msg/String.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(AgentCommand_SOURCE)
#define AgentCommand_DllAPI __declspec( dllexport )
#else
#define AgentCommand_DllAPI __declspec( dllimport )
#endif // AgentCommand_SOURCE
#else
#define AgentCommand_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define AgentCommand_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace custom_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure AgentCommand defined by the user in the IDL file.
         * @ingroup AGENTCOMMAND
         */
        class AgentCommand
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport AgentCommand();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~AgentCommand();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object custom_msgs::msg::AgentCommand that will be copied.
             */
            eProsima_user_DllExport AgentCommand(
                    const AgentCommand& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object custom_msgs::msg::AgentCommand that will be copied.
             */
            eProsima_user_DllExport AgentCommand(
                    AgentCommand&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object custom_msgs::msg::AgentCommand that will be copied.
             */
            eProsima_user_DllExport AgentCommand& operator =(
                    const AgentCommand& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object custom_msgs::msg::AgentCommand that will be copied.
             */
            eProsima_user_DllExport AgentCommand& operator =(
                    AgentCommand&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x custom_msgs::msg::AgentCommand object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const AgentCommand& x) const;

            /*!
             * @brief Comparison operator.
             * @param x custom_msgs::msg::AgentCommand object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const AgentCommand& x) const;

            /*!
             * @brief This function copies the value in member agents
             * @param _agents New value to be copied in member agents
             */
            eProsima_user_DllExport void agents(
                    const std::vector<std_msgs::msg::Int8>& _agents);

            /*!
             * @brief This function moves the value in member agents
             * @param _agents New value to be moved in member agents
             */
            eProsima_user_DllExport void agents(
                    std::vector<std_msgs::msg::Int8>&& _agents);

            /*!
             * @brief This function returns a constant reference to member agents
             * @return Constant reference to member agents
             */
            eProsima_user_DllExport const std::vector<std_msgs::msg::Int8>& agents() const;

            /*!
             * @brief This function returns a reference to member agents
             * @return Reference to member agents
             */
            eProsima_user_DllExport std::vector<std_msgs::msg::Int8>& agents();
            /*!
             * @brief This function copies the value in member command
             * @param _command New value to be copied in member command
             */
            eProsima_user_DllExport void command(
                    const std_msgs::msg::String& _command);

            /*!
             * @brief This function moves the value in member command
             * @param _command New value to be moved in member command
             */
            eProsima_user_DllExport void command(
                    std_msgs::msg::String&& _command);

            /*!
             * @brief This function returns a constant reference to member command
             * @return Constant reference to member command
             */
            eProsima_user_DllExport const std_msgs::msg::String& command() const;

            /*!
             * @brief This function returns a reference to member command
             * @return Reference to member command
             */
            eProsima_user_DllExport std_msgs::msg::String& command();
            /*!
             * @brief This function copies the value in member target
             * @param _target New value to be copied in member target
             */
            eProsima_user_DllExport void target(
                    const std::vector<geometry_msgs::msg::Point>& _target);

            /*!
             * @brief This function moves the value in member target
             * @param _target New value to be moved in member target
             */
            eProsima_user_DllExport void target(
                    std::vector<geometry_msgs::msg::Point>&& _target);

            /*!
             * @brief This function returns a constant reference to member target
             * @return Constant reference to member target
             */
            eProsima_user_DllExport const std::vector<geometry_msgs::msg::Point>& target() const;

            /*!
             * @brief This function returns a reference to member target
             * @return Reference to member target
             */
            eProsima_user_DllExport std::vector<geometry_msgs::msg::Point>& target();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const custom_msgs::msg::AgentCommand& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::vector<std_msgs::msg::Int8> m_agents;
            std_msgs::msg::String m_command;
            std::vector<geometry_msgs::msg::Point> m_target;

        };
    } // namespace msg
} // namespace custom_msgs

#endif // _FAST_DDS_GENERATED_CUSTOM_MSGS_MSG_AGENTCOMMAND_H_